//! Controlled Port state machine per IEEE 802.1X-2020, Clause 10.
//!
//! Implements: #29 (REQ-F-CP-001: CP State Machine)
//! Architecture: #74 (ADR-SM-002), #76 (ADR-SEC-004)
//!
//! IMPORTANT: This implementation is based on understanding of IEEE 802.1X-2020.
//! No copyrighted content from the standard is reproduced.

use crate::mka::{CipherSuite, Sak, Sci};

/// Controlled Port state.
///
/// Per IEEE 802.1X-2020, Clause 10.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CpState {
    /// Controlled Port is disabled (blocked).
    Disabled,
    /// Controlled Port is unsecured (open, no MACsec).
    Unsecured,
    /// Controlled Port is secured (MACsec active).
    Secured,
}

/// Events that drive CP state transitions.
///
/// Per IEEE 802.1X-2020, Clause 10.
#[derive(Debug)]
pub enum CpEvent {
    /// Logon Process requests port enable (unsecured).
    EnableUnsecured,
    /// Logon Process or MKA requests port disable.
    Disable,
    /// MKA has produced a new SAK for installation.
    SakAvailable {
        /// The SAK to install.
        sak: Sak,
        /// SCI for the secure channel.
        sci: Sci,
        /// Cipher suite for the secure channel.
        cipher_suite: CipherSuite,
    },
    /// SAK retire timer expired.
    SakRetireExpired,
}

/// Secure Channel — represents an active MACsec secure channel.
///
/// Per IEEE 802.1X-2020, Clause 10.
#[derive(Debug, Clone)]
pub struct SecureChannel {
    /// SCI for this channel.
    sci: Sci,
    /// Cipher suite in use.
    cipher_suite: CipherSuite,
    /// Channel offset for XPN mode.
    offset: u64,
}

impl SecureChannel {
    /// Create a new secure channel.
    pub fn new(sci: Sci, cipher_suite: CipherSuite) -> Self {
        Self {
            sci,
            cipher_suite,
            offset: 0,
        }
    }

    /// SCI for this channel.
    pub fn sci(&self) -> &Sci {
        &self.sci
    }

    /// Cipher suite in use.
    pub fn cipher_suite(&self) -> CipherSuite {
        self.cipher_suite
    }

    /// Channel offset (XPN mode).
    pub fn offset(&self) -> u64 {
        self.offset
    }
}

/// Secure Association — represents a SAK within a Secure Channel.
///
/// Per IEEE 802.1X-2020, Clause 10.
#[derive(Debug, Clone)]
pub struct SecureAssociation {
    /// Association Number (AN), 0-3.
    an: u8,
    /// Whether this SA is receiving.
    receiving: bool,
    /// Whether this SA is transmitting.
    transmitting: bool,
}

impl SecureAssociation {
    /// Create a new secure association.
    pub fn new(an: u8) -> Self {
        Self {
            an,
            receiving: true,
            transmitting: true,
        }
    }

    /// Association Number.
    pub fn an(&self) -> u8 {
        self.an
    }

    /// Whether this SA is receiving.
    pub fn is_receiving(&self) -> bool {
        self.receiving
    }

    /// Whether this SA is transmitting.
    pub fn is_transmitting(&self) -> bool {
        self.transmitting
    }
}

/// CP State Machine — manages Controlled Port transitions.
///
/// Per IEEE 802.1X-2020, Clause 10.
/// Transitions driven by MKA SAK installation and Logon Process.
///
/// State transitions (INV-PAE-006):
/// - `Disabled` → `Unsecured`: on `EnableUnsecured`
/// - `Unsecured` → `Secured`: on `SakAvailable`
/// - `Secured` → `Disabled`: on `Disable`
/// - `Unsecured` → `Disabled`: on `Disable`
/// - `Secured` → `Unsecured`: on `SakRetireExpired` (SAK retired, fall back)
pub struct CpStateMachine {
    /// Current CP state.
    state: CpState,
    /// Port identifier.
    port_id: u32,
    /// Current Secure Channel (if in Secured state).
    secure_channel: Option<SecureChannel>,
    /// Current Secure Association (if SAK installed).
    current_sa: Option<SecureAssociation>,
}

impl CpStateMachine {
    /// Create a new CP state machine in Disabled state. Per Cl.10.
    pub fn new(port_id: u32) -> Self {
        Self {
            state: CpState::Disabled,
            port_id,
            secure_channel: None,
            current_sa: None,
        }
    }

    /// Process a CP event. Per Cl.10.
    ///
    /// Returns events generated by the transition.
    ///
    /// # Errors
    /// Returns `PaeError::InvalidTransition` for invalid transitions.
    pub fn handle_event(&mut self, event: CpEvent) -> Result<Vec<CpTransition>, crate::PaeError> {
        match event {
            CpEvent::EnableUnsecured => self.enable_unsecured(),
            CpEvent::Disable => self.disable(),
            CpEvent::SakAvailable {
                sak,
                sci,
                cipher_suite,
            } => self.install_sak(sak, sci, cipher_suite),
            CpEvent::SakRetireExpired => self.retire_sak(),
        }
    }

    /// Current CP state.
    pub fn state(&self) -> CpState {
        self.state
    }

    /// Port identifier.
    pub fn port_id(&self) -> u32 {
        self.port_id
    }

    /// Current secure channel, if any.
    pub fn secure_channel(&self) -> Option<&SecureChannel> {
        self.secure_channel.as_ref()
    }

    /// Current secure association, if any.
    pub fn current_sa(&self) -> Option<&SecureAssociation> {
        self.current_sa.as_ref()
    }

    /// Whether the Controlled Port is MAC_Operational.
    ///
    /// Per Cl.10: the port is operational in Unsecured or Secured states.
    pub fn is_operational(&self) -> bool {
        matches!(self.state, CpState::Unsecured | CpState::Secured)
    }

    /// Whether MACsec protection is active.
    pub fn is_macsec_active(&self) -> bool {
        self.state == CpState::Secured
    }

    fn enable_unsecured(&mut self) -> Result<Vec<CpTransition>, crate::PaeError> {
        match self.state {
            CpState::Disabled => {
                self.state = CpState::Unsecured;
                Ok(vec![CpTransition::ToUnsecured {
                    port_id: self.port_id,
                }])
            }
            CpState::Unsecured => Ok(vec![]), // Already unsecured, no-op
            CpState::Secured => Err(crate::PaeError::InvalidTransition {
                from: "Secured".into(),
                to: "Unsecured".into(),
            }),
        }
    }

    fn disable(&mut self) -> Result<Vec<CpTransition>, crate::PaeError> {
        match self.state {
            CpState::Disabled => Ok(vec![]), // Already disabled, no-op
            CpState::Unsecured => {
                self.state = CpState::Disabled;
                Ok(vec![CpTransition::ToDisabled {
                    port_id: self.port_id,
                }])
            }
            CpState::Secured => {
                self.secure_channel = None;
                self.current_sa = None;
                self.state = CpState::Disabled;
                Ok(vec![CpTransition::ToDisabled {
                    port_id: self.port_id,
                }])
            }
        }
    }

    fn install_sak(
        &mut self,
        sak: Sak,
        sci: Sci,
        cipher_suite: CipherSuite,
    ) -> Result<Vec<CpTransition>, crate::PaeError> {
        match self.state {
            CpState::Disabled => Err(crate::PaeError::InvalidTransition {
                from: "Disabled".into(),
                to: "Secured".into(),
            }),
            CpState::Unsecured => {
                let an = sak.an();
                self.secure_channel = Some(SecureChannel::new(sci, cipher_suite));
                self.current_sa = Some(SecureAssociation::new(an));
                self.state = CpState::Secured;
                Ok(vec![CpTransition::ToSecured {
                    port_id: self.port_id,
                }])
            }
            CpState::Secured => {
                // Replace SAK in already-secured state (SAK rekey)
                let an = sak.an();
                self.current_sa = Some(SecureAssociation::new(an));
                Ok(vec![CpTransition::SakRekeyed {
                    port_id: self.port_id,
                }])
            }
        }
    }

    fn retire_sak(&mut self) -> Result<Vec<CpTransition>, crate::PaeError> {
        match self.state {
            CpState::Secured => {
                self.current_sa = None;
                self.secure_channel = None;
                self.state = CpState::Unsecured;
                Ok(vec![CpTransition::ToUnsecured {
                    port_id: self.port_id,
                }])
            }
            CpState::Unsecured | CpState::Disabled => {
                // No SAK to retire; no-op
                Ok(vec![])
            }
        }
    }
}

/// CP state transition outcomes.
///
/// Returned by `CpStateMachine::handle_event()` to signal what happened.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CpTransition {
    /// Port transitioned to Unsecured.
    ToUnsecured {
        /// Port identifier.
        port_id: u32,
    },
    /// Port transitioned to Secured.
    ToSecured {
        /// Port identifier.
        port_id: u32,
    },
    /// Port transitioned to Disabled.
    ToDisabled {
        /// Port identifier.
        port_id: u32,
    },
    /// SAK was rekeyed (stayed in Secured).
    SakRekeyed {
        /// Port identifier.
        port_id: u32,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per IEEE 802.1X-2020, Clause 10.
    /// CP state machine starts in Disabled state.
    #[test]
    fn test_cp_initial_state() {
        let cp = CpStateMachine::new(1);
        assert_eq!(cp.state(), CpState::Disabled);
        assert!(!cp.is_operational());
        assert!(!cp.is_macsec_active());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per Cl.10: Disabled → Unsecured on EnableUnsecured.
    #[test]
    fn test_cp_disabled_to_unsecured() {
        let mut cp = CpStateMachine::new(1);
        let transitions = cp
            .handle_event(CpEvent::EnableUnsecured)
            .expect("EnableUnsecured should succeed");
        assert_eq!(cp.state(), CpState::Unsecured);
        assert!(cp.is_operational());
        assert!(!cp.is_macsec_active());
        assert_eq!(transitions, vec![CpTransition::ToUnsecured { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per Cl.10: Unsecured → Secured on SakAvailable.
    #[test]
    fn test_cp_unsecured_to_secured() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();

        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        let transitions = cp
            .handle_event(CpEvent::SakAvailable {
                sak,
                sci,
                cipher_suite: CipherSuite::GcmAes128,
            })
            .expect("SakAvailable should succeed");
        assert_eq!(cp.state(), CpState::Secured);
        assert!(cp.is_operational());
        assert!(cp.is_macsec_active());
        assert!(cp.secure_channel().is_some());
        assert!(cp.current_sa().is_some());
        assert_eq!(transitions, vec![CpTransition::ToSecured { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per Cl.10: Full cycle Disabled → Unsecured → Secured → Disabled.
    #[test]
    fn test_cp_full_cycle() {
        let mut cp = CpStateMachine::new(1);

        // Disabled → Unsecured
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        assert_eq!(cp.state(), CpState::Unsecured);

        // Unsecured → Secured
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();
        assert_eq!(cp.state(), CpState::Secured);

        // Secured → Disabled
        let transitions = cp.handle_event(CpEvent::Disable).unwrap();
        assert_eq!(cp.state(), CpState::Disabled);
        assert!(cp.secure_channel().is_none());
        assert!(cp.current_sa().is_none());
        assert_eq!(transitions, vec![CpTransition::ToDisabled { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per Cl.10: Secured → Unsecured on SakRetireExpired.
    #[test]
    fn test_cp_sak_retire() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();
        assert_eq!(cp.state(), CpState::Secured);

        let transitions = cp
            .handle_event(CpEvent::SakRetireExpired)
            .expect("SakRetireExpired should succeed");
        assert_eq!(cp.state(), CpState::Unsecured);
        assert!(cp.is_operational());
        assert!(!cp.is_macsec_active());
        assert!(cp.secure_channel().is_none());
        assert_eq!(transitions, vec![CpTransition::ToUnsecured { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// SAK rekey in Secured state stays in Secured.
    #[test]
    fn test_cp_sak_rekey() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let sak1 = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci1 = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak: sak1,
            sci: sci1,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();

        // Rekey with new SAK (AN=1)
        let sak2 = Sak::from_bytes(&[0x03; 16], 1).unwrap();
        let sci2 = Sci::new([0x04; 6], 1);
        let transitions = cp
            .handle_event(CpEvent::SakAvailable {
                sak: sak2,
                sci: sci2,
                cipher_suite: CipherSuite::GcmAes128,
            })
            .expect("SAK rekey should succeed");
        assert_eq!(cp.state(), CpState::Secured);
        assert_eq!(cp.current_sa().unwrap().an(), 1);
        assert_eq!(transitions, vec![CpTransition::SakRekeyed { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Disabled → Secured is invalid.
    #[test]
    fn test_cp_disabled_to_secured_invalid() {
        let mut cp = CpStateMachine::new(1);
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        let result = cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        });
        assert!(result.is_err());
        assert_eq!(cp.state(), CpState::Disabled);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Secured → Unsecured via EnableUnsecured is invalid.
    #[test]
    fn test_cp_secured_to_unsecured_invalid() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();

        let result = cp.handle_event(CpEvent::EnableUnsecured);
        assert!(result.is_err());
        assert_eq!(cp.state(), CpState::Secured);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Disable on already-Disabled is a no-op.
    #[test]
    fn test_cp_disable_noop() {
        let mut cp = CpStateMachine::new(1);
        let transitions = cp
            .handle_event(CpEvent::Disable)
            .expect("Disable on Disabled should be no-op");
        assert_eq!(cp.state(), CpState::Disabled);
        assert!(transitions.is_empty());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// EnableUnsecured on already-Unsecured is a no-op.
    #[test]
    fn test_cp_enable_unsecured_noop() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let transitions = cp
            .handle_event(CpEvent::EnableUnsecured)
            .expect("EnableUnsecured on Unsecured should be no-op");
        assert_eq!(cp.state(), CpState::Unsecured);
        assert!(transitions.is_empty());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// SakRetireExpired on Unsecured/Disabled is a no-op.
    #[test]
    fn test_cp_retire_noop() {
        let mut cp = CpStateMachine::new(1);
        let transitions = cp
            .handle_event(CpEvent::SakRetireExpired)
            .expect("SakRetire on Disabled should be no-op");
        assert!(transitions.is_empty());

        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let transitions = cp
            .handle_event(CpEvent::SakRetireExpired)
            .expect("SakRetire on Unsecured should be no-op");
        assert!(transitions.is_empty());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Unsecured → Disabled on Disable.
    #[test]
    fn test_cp_unsecured_to_disabled() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let transitions = cp
            .handle_event(CpEvent::Disable)
            .expect("Disable should succeed");
        assert_eq!(cp.state(), CpState::Disabled);
        assert!(!cp.is_operational());
        assert_eq!(transitions, vec![CpTransition::ToDisabled { port_id: 1 }]);
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Secure channel and association are set correctly on SAK install.
    #[test]
    fn test_cp_secure_channel_after_sak() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let sak = Sak::from_bytes(&[0x01; 16], 2).unwrap();
        let sci = Sci::new([0xAA; 6], 42);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes256,
        })
        .unwrap();

        let sc = cp.secure_channel().expect("secure channel should exist");
        assert_eq!(sc.sci().mac(), &[0xAA; 6]);
        assert_eq!(sc.sci().port(), 42);
        assert_eq!(sc.cipher_suite(), CipherSuite::GcmAes256);

        let sa = cp.current_sa().expect("secure association should exist");
        assert_eq!(sa.an(), 2);
        assert!(sa.is_receiving());
        assert!(sa.is_transmitting());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per REQ-F-CP-001 acceptance: authentication succeeds and MKA establishes
    /// secured connectivity → controlledPortEnabled → MAC_Operational.
    #[test]
    fn test_cp_acceptance_secured() {
        let mut cp = CpStateMachine::new(1);
        // Authentication succeeds → EnableUnsecured
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        assert!(cp.is_operational());

        // MKA establishes secured connectivity → SakAvailable
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();
        assert!(cp.is_operational());
        assert!(cp.is_macsec_active());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per REQ-F-CP-001 acceptance: MKA fails → controlledPortEnabled cleared →
    /// Controlled Port MAC_Operational=FALSE.
    #[test]
    fn test_cp_acceptance_mka_fails() {
        let mut cp = CpStateMachine::new(1);
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        let sak = Sak::from_bytes(&[0x01; 16], 0).unwrap();
        let sci = Sci::new([0x02; 6], 1);
        cp.handle_event(CpEvent::SakAvailable {
            sak,
            sci,
            cipher_suite: CipherSuite::GcmAes128,
        })
        .unwrap();

        // MKA fails → Disable
        cp.handle_event(CpEvent::Disable).unwrap();
        assert!(!cp.is_operational());
        assert!(!cp.is_macsec_active());
    }

    /// Verifies: #29 (REQ-F-CP-001)
    /// Per REQ-F-CP-001 acceptance: authentication succeeds without MACsec →
    /// controlledPortEnabled without MACsec protection.
    #[test]
    fn test_cp_acceptance_unsecured() {
        let mut cp = CpStateMachine::new(1);
        // Authentication succeeds without MACsec → EnableUnsecured
        cp.handle_event(CpEvent::EnableUnsecured).unwrap();
        assert!(cp.is_operational());
        assert!(!cp.is_macsec_active());
    }
}
